name: clock_pro
description: Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  get: ^4.6.5
  google_fonts: ^5.1.0
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  icons_plus: ^4.0.0
  rename: ^2.1.1
  stop_watch_timer: ^2.0.0
  timezone: ^0.9.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
